version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "random-verse"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15m2b62cchezx"
s3_prefix = "random-verse"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
